# Database configuration

# MongoDB connection string
mongo="mongodb://127.0.0.1:27017/wildduck"

# Redis connection string
redis="redis://localhost:6379/2"

# Database name for ZoneMTA data in MongoDB
sender="zone-mta"

# Database name for Wild Duck users
users="wildduck"

# Database name for Wild Duck attachments
gridfs="wildduck"
